### ISSUE TITLE
Make it possible to choose Feiertage based on Bundesland

### ISSUE THREAD

**Issue by baderas** [MariusLang/node-red-contrib-feiertage-germany#18]
**Is your feature request related to a problem? Please describe.**
Some Feiertage in Germany are not available to every Bundesland. Therefore, this solution only works for bundesweite Feiertage.

**Describe the solution you'd like**
An Option to choose a Bundesland for which it can be checked if today is a Feiertag.

**Comment by MariusLang** [comment]
Hi @baderas,

you can simply select select the holidays you need by checking (or unchecking) the checkbox in the row before each holiday (see example below). If the checkbox isn't checked, it will be ignored in your holiday calendar (you won't receive notifications for unchecked holidays and it won't be considered in specific requests made through the node input).

holiday checked: <img width="347" alt="Bildschirm­foto 2022-11-12 um 21 48 03" src="https://user-images.githubusercontent.com/60567441/201493982-dfd7067b-16dc-4d0b-816f-54e9991b16f9.png">

holiday unchecked: <img width="346" alt="Bildschirm­foto 2022-11-12 um 21 52 55" src="https://user-images.githubusercontent.com/60567441/201494111-bdec02ed-735d-4b33-b98e-790e0c53fbb7.png">


Therefore, you have the possibility to build your own holiday calendar suiting your needs perfectly.

Are there any holidays missing in **node-red-contrib-feiertage-germany**? Feel free to contact me. I'm going to add them immediately.

Kind regards
Marius
