### ISSUE TITLE
isTomorrowHoliday

### ISSUE THREAD

**Issue by btro1404** [MariusLang/node-red-contrib-feiertage-germany#21]
For my home automation (roller shutter control) I would like to have an boolean whether tomorrow is a holiday because then I go to bed later. Maybe in the future it could also be interesting to know whether yesterday was a holiday. Okay, I could remember that in a variable, but maybe the effort involved in implementing a new function "isTomorrowHoliday" (or "willTomorrowHoliday") isn't too great to also include an "isYesterdayHoliday" (or "wasYesterdayHoliday") ?

**Comment by MariusLang** [comment]
Thanks for pointing out that enhancement. It'll be implemented in an upcoming version that will be released in a few days.

**Comment by MariusLang** [comment]
I have implemented the requested functionallity to request whether tomorrow is a holiday. Use the msg.payload `isTomorrowHoliday` as input to test the functionallity. For further information read the doc - especially ![this section](https://github.com/MariusLang/node-red-contrib-feiertage-germany#node-description).

The feature `wasYesterdayHoliday` will be released in a future version. Here is more refactoring necessary than I initially thought. However, don't worry even if I'm closing this issue it's on my todo list.
